## Configuracion de Spring
spring:
  application:
    name: ms-inventory-products

## Configuracion de Instancia 
server:
  port: 8088
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-inventory-products
    instance-id: ${spring.application.name}:${random.uuid}

##Elasticsearch config
elasticsearch:
  host: cluster-unir-4352502836.us-east-1.bonsaisearch.net
  credentials:
    user: uy92sz462u
    password: gdkhabv26c
logging:
  level:
    tracer: TRACE